services:
  unleash:
    image: unleashorg/unleash-server:${DIP_INFRA_UNLEASH_IMAGE_TAG}
    environment:
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DB}
      VIRTUAL_HOST: ${UNLEASH_HOSTNAME}
      VIRTUAL_PATH: /
      VIRTUAL_PORT: 80
      HTTP_PORT: 80
      UNLEASH_URL: http://${UNLEASH_HOSTNAME}
      DATABASE_SSL: false
      INIT_FRONTEND_API_TOKENS: ${INIT_FRONTEND_API_TOKENS}
      INIT_CLIENT_API_TOKENS: ${INIT_CLIENT_API_TOKENS}
    networks:
      default:
      nginx-net:
        aliases:
          - ${UNLEASH_HOSTNAME}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s

  postgres:
    image: postgres:${DIP_INFRA_UNLEASH_POSTGRES_IMAGE_TAG}
    environment:
      PSQL_HISTFILE: /user/local/hist/.psql_history
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER} -h 127.0.0.1
      interval: 5s
    volumes:
      - postgres:/var/lib/postgresql/data
      - history:/user/local/hist
    ports:
      - "${UNLEASH_POSTGRES_HOST_PORT:-54323}:5432"

volumes:
  postgres:
  history:
networks:
  default:
    name: ${DIP_INFRA_NETWORK_NAME}
    external: true
  nginx-net:
    name: ${DIP_INFRA_NETWORK_NGINX}
    external: true
